import { useState, useRef } from "react";

const CONTACT = { tel: "15817486316", telDisplay: "581-748-6316" };
const DISCOUNTS = [
  { min: 0,   max: 99,       pct: 0  },
  { min: 100, max: 199,      pct: 10 },
  { min: 200, max: 399,      pct: 15 },
  { min: 400, max: Infinity, pct: 20 },
];
const WHEEL = [
  { label:"5% EXTRA",  pct:5,  prob:40, color:"#d4af37" },
  { label:"10% EXTRA", pct:10, prob:30, color:"#c9a84c" },
  { label:"15% EXTRA", pct:15, prob:20, color:"#e8c96a" },
  { label:"20% EXTRA", pct:20, prob:10, color:"#f7e098" },
];
const CARDS = [
  {id:1,  joueur:"Gabe Vilardi",          annee:"2021-22",collection:"OPC Platinum",        numero:"#103", variante:"",                  equipe:"Kings",      prix:3,    dispo:true},
  {id:2,  joueur:"Victor Olofsson",       annee:"2021-22",collection:"OPC Platinum",        numero:"#118", variante:"",                  equipe:"Sabres",     prix:2,    dispo:true},
  {id:3,  joueur:"Jordan Staal",          annee:"2021-22",collection:"OPC Platinum",        numero:"#81",  variante:"",                  equipe:"Hurricanes", prix:2,    dispo:true},
  {id:4,  joueur:"Jonathan Marchessault", annee:"2021-22",collection:"OPC Platinum",        numero:"#185", variante:"Rainbow",           equipe:"Knights",    prix:15,   dispo:true},
  {id:5,  joueur:"Josh Norris",           annee:"2021-22",collection:"OPC Platinum",        numero:"#93",  variante:"",                  equipe:"Senators",   prix:3,    dispo:true},
  {id:6,  joueur:"Ryan Strome",           annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Rangers",    prix:2,    dispo:true},
  {id:7,  joueur:"Jordan Kyrou",          annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Blues",      prix:3,    dispo:true},
  {id:8,  joueur:"Nino Niederreiter",     annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Hurricanes", prix:2,    dispo:true},
  {id:9,  joueur:"Kevin Fiala",           annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Wild",       prix:3,    dispo:true},
  {id:10, joueur:"Miro Heiskanen",        annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Stars",      prix:5,    dispo:true},
  {id:11, joueur:"Tomas Hertl",           annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Sharks",     prix:2,    dispo:true},
  {id:12, joueur:"Casey Mittelstadt",     annee:"2021-22",collection:"OPC Platinum",        numero:"",     variante:"",                  equipe:"Sabres",     prix:2,    dispo:true},
  {id:13, joueur:"Colton Parayko",        annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Blues",      prix:3,    dispo:true},
  {id:14, joueur:"Gabe Vilardi",          annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Kings",      prix:3,    dispo:true},
  {id:15, joueur:"Kevin Fiala",           annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Kings",      prix:3,    dispo:true},
  {id:16, joueur:"Jack Hughes",           annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Devils",     prix:8,    dispo:true},
  {id:17, joueur:"Matt Boldy",            annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Wild",       prix:3,    dispo:true},
  {id:18, joueur:"Mason McTavish",        annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Ducks",      prix:4,    dispo:true},
  {id:19, joueur:"Erik Karlsson",         annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Penguins",   prix:3,    dispo:true},
  {id:20, joueur:"Rasmus Dahlin",         annee:"2023-24",collection:"UD Trilogy",          numero:"#91",  variante:"",                  equipe:"Sabres",     prix:6,    dispo:true},
  {id:21, joueur:"Owen Power",            annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Sabres",     prix:4,    dispo:true},
  {id:22, joueur:"Noah Dobson",           annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Islanders",  prix:3,    dispo:true},
  {id:23, joueur:"Andrei Svechnikov",     annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Hurricanes", prix:4,    dispo:true},
  {id:24, joueur:"Brad Marchand",         annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Bruins",     prix:4,    dispo:true},
  {id:25, joueur:"Jonathan Marchessault", annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Knights",    prix:5,    dispo:true},
  {id:26, joueur:"Taylor Raddysh",        annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Blackhawks", prix:2,    dispo:true},
  {id:27, joueur:"Andrei Vasilevskiy",    annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Lightning",  prix:5,    dispo:true},
  {id:28, joueur:"Ryan Nugent-Hopkins",   annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Oilers",     prix:3,    dispo:true},
  {id:29, joueur:"Rasmus Dahlin",         annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Sabres",     prix:6,    dispo:true},
  {id:30, joueur:"Nikita Kucherov",       annee:"2023-24",collection:"UD Trilogy",          numero:"",     variante:"",                  equipe:"Lightning",  prix:8,    dispo:true},
  {id:31, joueur:"Jari Kurri",            annee:"2014-15",collection:"Fleer Showcase",      numero:"#3",   variante:"",                  equipe:"Rangers",    prix:4,    dispo:true},
  {id:32, joueur:"Adam Henrique",         annee:"2014-15",collection:"Fleer Showcase",      numero:"#4",   variante:"",                  equipe:"Devils",     prix:2,    dispo:true},
  {id:33, joueur:"Sean Couturier",        annee:"2014-15",collection:"Fleer Showcase",      numero:"#5",   variante:"Team Canada",       equipe:"Flyers",     prix:3,    dispo:true},
  {id:34, joueur:"Shea Weber",            annee:"2014-15",collection:"Fleer Showcase",      numero:"#6",   variante:"",                  equipe:"Predators",  prix:3,    dispo:true},
  {id:35, joueur:"Max Pacioretty",        annee:"2014-15",collection:"Fleer Showcase",      numero:"#10",  variante:"",                  equipe:"Canadiens",  prix:3,    dispo:true},
  {id:36, joueur:"Matt Duchene",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#14",  variante:"",                  equipe:"Avalanche",  prix:3,    dispo:true},
  {id:37, joueur:"Tuukka Rask",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#15",  variante:"",                  equipe:"Bruins",     prix:3,    dispo:true},
  {id:38, joueur:"Chris Osgood",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#18",  variante:"",                  equipe:"Red Wings",  prix:3,    dispo:true},
  {id:39, joueur:"Ryan Johansen",         annee:"2014-15",collection:"Fleer Showcase",      numero:"#19",  variante:"Team Canada",       equipe:"Predators",  prix:2,    dispo:true},
  {id:40, joueur:"Brendan Gallagher",     annee:"2014-15",collection:"Fleer Showcase",      numero:"#20",  variante:"",                  equipe:"Canadiens",  prix:3,    dispo:true},
  {id:41, joueur:"Brett Hull",            annee:"2014-15",collection:"Fleer Showcase",      numero:"#22",  variante:"",                  equipe:"Stars",      prix:6,    dispo:true},
  {id:42, joueur:"Steven Stamkos",        annee:"2014-15",collection:"Fleer Showcase",      numero:"#23",  variante:"",                  equipe:"Lightning",  prix:5,    dispo:true},
  {id:43, joueur:"Glen Murray",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#25",  variante:"",                  equipe:"Bruins",     prix:2,    dispo:true},
  {id:44, joueur:"Doug Weight",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#30",  variante:"",                  equipe:"Oilers",     prix:2,    dispo:true},
  {id:45, joueur:"Patrick Marleau",       annee:"2014-15",collection:"Fleer Showcase",      numero:"#32",  variante:"",                  equipe:"Sharks",     prix:3,    dispo:true},
  {id:46, joueur:"Zdeno Chara",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#35",  variante:"",                  equipe:"Bruins",     prix:4,    dispo:true},
  {id:47, joueur:"John Tavares",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#36",  variante:"",                  equipe:"Islanders",  prix:5,    dispo:true},
  {id:48, joueur:"Wayne Simmonds",        annee:"2014-15",collection:"Fleer Showcase",      numero:"#39",  variante:"",                  equipe:"Flyers",     prix:2,    dispo:true},
  {id:49, joueur:"Semyon Varlamov",       annee:"2014-15",collection:"Fleer Showcase",      numero:"#40",  variante:"",                  equipe:"Avalanche",  prix:2,    dispo:true},
  {id:50, joueur:"Dominik Hasek",         annee:"2014-15",collection:"Fleer Showcase",      numero:"#44",  variante:"",                  equipe:"Red Wings",  prix:8,    dispo:true},
  {id:51, joueur:"Ryan Getzlaf",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#48",  variante:"",                  equipe:"Ducks",      prix:3,    dispo:true},
  {id:52, joueur:"Zack Kassian",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#50",  variante:"Team Canada",       equipe:"Oilers",     prix:2,    dispo:true},
  {id:53, joueur:"Evander Kane",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#51",  variante:"",                  equipe:"Jets",       prix:2,    dispo:true},
  {id:54, joueur:"Karri Ramo",            annee:"2014-15",collection:"Fleer Showcase",      numero:"#52",  variante:"",                  equipe:"Flames",     prix:2,    dispo:true},
  {id:55, joueur:"Claude Giroux",         annee:"2014-15",collection:"Fleer Showcase",      numero:"#53",  variante:"",                  equipe:"Flyers",     prix:3,    dispo:true},
  {id:56, joueur:"Johan Franzen",         annee:"2014-15",collection:"Fleer Showcase",      numero:"#56",  variante:"",                  equipe:"Red Wings",  prix:2,    dispo:true},
  {id:57, joueur:"Phil Kessel",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#59",  variante:"",                  equipe:"Maple Leafs",prix:3,    dispo:true},
  {id:58, joueur:"Jonathan Bernier",      annee:"2014-15",collection:"Fleer Showcase",      numero:"#60",  variante:"",                  equipe:"Maple Leafs",prix:2,    dispo:true},
  {id:59, joueur:"Jake Muzzin",           annee:"2014-15",collection:"Fleer Showcase",      numero:"#61",  variante:"",                  equipe:"Kings",      prix:2,    dispo:true},
  {id:60, joueur:"Matt Moulson",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#64",  variante:"",                  equipe:"Sabres",     prix:2,    dispo:true},
  {id:61, joueur:"Henrik Zetterberg",     annee:"2014-15",collection:"Fleer Showcase",      numero:"#67",  variante:"",                  equipe:"Red Wings",  prix:5,    dispo:true},
  {id:62, joueur:"Sean Monahan",          annee:"2014-15",collection:"Fleer Showcase",      numero:"#70",  variante:"",                  equipe:"Flames",     prix:3,    dispo:true},
  {id:63, joueur:"Andrei Vasilevskiy",    annee:"2014-15",collection:"Fleer Showcase",      numero:"",     variante:"",                  equipe:"Lightning",  prix:8,    dispo:true},
  {id:64, joueur:"Martin Hanzal",         annee:"2014-15",collection:"Upper Deck MVP",      numero:"#107", variante:"",                  equipe:"Coyotes",    prix:2,    dispo:true},
  {id:65, joueur:"Brent Seabrook",        annee:"2014-15",collection:"Upper Deck MVP",      numero:"#111", variante:"",                  equipe:"Blackhawks", prix:2,    dispo:true},
  {id:66, joueur:"Wayne Gretzky",         annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"Alumni",            equipe:"Oilers",     prix:8,    dispo:true},
  {id:67, joueur:"Adam Oates",            annee:"2023-24",collection:"Tim Hortons",         numero:"#49",  variante:"Alumni",            equipe:"Bruins",     prix:4,    dispo:true},
  {id:68, joueur:"Mark Messier",          annee:"2023-24",collection:"Tim Hortons",         numero:"#27",  variante:"Alumni",            equipe:"Rangers",    prix:6,    dispo:true},
  {id:69, joueur:"Ray Bourque",           annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"Alumni",            equipe:"Bruins",     prix:6,    dispo:true},
  {id:70, joueur:"Brian Leetch",          annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"Alumni",            equipe:"Rangers",    prix:4,    dispo:true},
  {id:71, joueur:"Jari Kurri",            annee:"2023-24",collection:"Tim Hortons",         numero:"#70",  variante:"Alumni",            equipe:"Oilers",     prix:4,    dispo:true},
  {id:72, joueur:"Joe Sakic",             annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"",                  equipe:"Avalanche",  prix:4,    dispo:true},
  {id:73, joueur:"Alex Ovechkin",         annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"",                  equipe:"Capitals",   prix:6,    dispo:true},
  {id:74, joueur:"Connor McDavid",        annee:"2023-24",collection:"Tim Hortons",         numero:"#25",  variante:"",                  equipe:"Oilers",     prix:12,   dispo:true},
  {id:75, joueur:"Leon Draisaitl",        annee:"2023-24",collection:"Tim Hortons",         numero:"#5",   variante:"",                  equipe:"Oilers",     prix:8,    dispo:true},
  {id:76, joueur:"Sidney Crosby",         annee:"2023-24",collection:"Tim Hortons",         numero:"",     variante:"",                  equipe:"Penguins",   prix:10,   dispo:true},
  {id:77, joueur:"Nathan MacKinnon",      annee:"2023-24",collection:"Tim Hortons",         numero:"#25",  variante:"",                  equipe:"Avalanche",  prix:10,   dispo:true},
  {id:78, joueur:"Evgeny Kuznetsov",      annee:"2023-24",collection:"Tim Hortons",         numero:"#7",   variante:"",                  equipe:"Capitals",   prix:3,    dispo:true},
  {id:79, joueur:"Lee Steckel",           annee:"2023-24",collection:"Tim Hortons",         numero:"#2",   variante:"",                  equipe:"",           prix:3,    dispo:true},
  {id:80, joueur:"Johnny Bower",          annee:"2023-24",collection:"Tim Hortons",         numero:"CL-6", variante:"UD Legends Alumni", equipe:"Maple Leafs",prix:6,    dispo:true},
  {id:81, joueur:"Quinn Hughes",          annee:"2024-25",collection:"Tim Hortons",         numero:"FH-13",variante:"Frozen Hotshots",   equipe:"Canucks",    prix:8,    dispo:true},
  {id:82, joueur:"Jack Hughes",           annee:"2024-25",collection:"Tim Hortons",         numero:"FH-2", variante:"Frozen Hotshots",   equipe:"Devils",     prix:10,   dispo:true},
  {id:83, joueur:"Nikita Kucherov",       annee:"2024-25",collection:"Tim Hortons",         numero:"FH-14",variante:"Frozen Hotshots",   equipe:"Lightning",  prix:8,    dispo:true},
  {id:84, joueur:"Mikko Rantanen",        annee:"2024-25",collection:"Tim Hortons",         numero:"FH-11",variante:"Frozen Hotshots",   equipe:"Avalanche",  prix:6,    dispo:true},
  {id:85, joueur:"Connor Bedard",         annee:"2024-25",collection:"Tim Hortons",         numero:"FH-5", variante:"Frozen Hotshots",   equipe:"Blackhawks", prix:12,   dispo:true},
  {id:86, joueur:"Auston Matthews",       annee:"2024-25",collection:"Tim Hortons",         numero:"FH-17",variante:"Frozen Hotshots",   equipe:"Maple Leafs",prix:15,   dispo:true},
  {id:87, joueur:"Victoria Bach",         annee:"2023-24",collection:"Tim Hortons",         numero:"#95",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:88, joueur:"Hannah Brandt",         annee:"2023-24",collection:"Tim Hortons",         numero:"#98",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:89, joueur:"Hayley Scamurra",       annee:"2023-24",collection:"Tim Hortons",         numero:"#90",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:90, joueur:"Megan Keller",          annee:"2023-24",collection:"Tim Hortons",         numero:"#97",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:91, joueur:"Jamie Lee Rattray",     annee:"2023-24",collection:"Tim Hortons",         numero:"#91",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:92, joueur:"Jaime Bourbonnais",     annee:"2023-24",collection:"Tim Hortons",         numero:"#14",  variante:"PWHL",              equipe:"PWHL",       prix:3,    dispo:true},
  {id:93, joueur:"Ryan O'Reilly",         annee:"2021-22",collection:"SP Authentic",        numero:"TL-7", variante:"True Leaders",      equipe:"Blues",      prix:5,    dispo:true},
  {id:94, joueur:"Nolan Allan",           annee:"2022-23",collection:"Team Canada Juniors", numero:"GT-24",variante:"Go To Top",         equipe:"Canada",     prix:4,    dispo:true},
  {id:95, joueur:"Blayre Turnbull",       annee:"2023-24",collection:"UD PWHL",             numero:"#40",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:96, joueur:"Emerance Maschmeyer",   annee:"2023-24",collection:"UD PWHL",             numero:"#88",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:97, joueur:"Marie-Philip Poulin",   annee:"2023-24",collection:"UD PWHL",             numero:"#29",  variante:"",                  equipe:"PWHL",       prix:8,    dispo:true},
  {id:98, joueur:"Nicole Hensley",        annee:"2023-24",collection:"UD PWHL",             numero:"#9",   variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:99, joueur:"Brianne Jenner",        annee:"2023-24",collection:"UD PWHL",             numero:"#19",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:100,joueur:"Abby Roque",            annee:"2023-24",collection:"UD PWHL",             numero:"#11",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:101,joueur:"Hilary Knight",         annee:"2023-24",collection:"UD PWHL",             numero:"#99",  variante:"",                  equipe:"PWHL",       prix:5,    dispo:true},
  {id:102,joueur:"Erin Ambrose",          annee:"2023-24",collection:"UD PWHL",             numero:"#100", variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:103,joueur:"Jessie Eldridge",       annee:"2023-24",collection:"UD PWHL",             numero:"#93",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:104,joueur:"Kristen Campbell",      annee:"2023-24",collection:"UD PWHL",             numero:"#94",  variante:"",                  equipe:"PWHL",       prix:3,    dispo:true},
  {id:105,joueur:"Ann-Renee Desbiens",    annee:"2023-24",collection:"UD PWHL",             numero:"#92",  variante:"",                  eq
